inherits:
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - duplicated

mypy:
  options:
    python-version: '3.10'

ruff:
  options:
    target-version: py310

pylint:
  disable:
    - no-member # Module {} has no {} member
    - no-name-in-module # No name {} in module {}
